// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOJWwEeRi9a73QeODGwMZTiK9WaPoc3G8',
    appId: '1:401664143901:web:32a59508dd70cef9d04cf4',
    messagingSenderId: '401664143901',
    projectId: 'doctorhub-1f3c2',
    authDomain: 'doctorhub-1f3c2.firebaseapp.com',
    storageBucket: 'doctorhub-1f3c2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB-u-uvJKbiq3yRFUpUNv3_FoDley06As',
    appId: '1:401664143901:android:7374aee0da1cd156d04cf4',
    messagingSenderId: '401664143901',
    projectId: 'doctorhub-1f3c2',
    storageBucket: 'doctorhub-1f3c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeulqe1waFzOWapiw0GTrZUo8dWZRyDvg',
    appId: '1:401664143901:ios:0efcaff3fa8b6adbd04cf4',
    messagingSenderId: '401664143901',
    projectId: 'doctorhub-1f3c2',
    storageBucket: 'doctorhub-1f3c2.firebasestorage.app',
    iosBundleId: 'com.example.appMed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeulqe1waFzOWapiw0GTrZUo8dWZRyDvg',
    appId: '1:401664143901:ios:0efcaff3fa8b6adbd04cf4',
    messagingSenderId: '401664143901',
    projectId: 'doctorhub-1f3c2',
    storageBucket: 'doctorhub-1f3c2.firebasestorage.app',
    iosBundleId: 'com.example.appMed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOJWwEeRi9a73QeODGwMZTiK9WaPoc3G8',
    appId: '1:401664143901:web:f02f784f307b1858d04cf4',
    messagingSenderId: '401664143901',
    projectId: 'doctorhub-1f3c2',
    authDomain: 'doctorhub-1f3c2.firebaseapp.com',
    storageBucket: 'doctorhub-1f3c2.firebasestorage.app',
  );
}
